// Ethiopian cities and locations for trip origin/destination selection
// This ensures consistency in location names across the application

export const LOCATIONS = [
    'Addis Ababa',
    'Adama (Nazret)',
    'Dire Dawa',
    'Mekelle',
    'Gondar',
    'Awassa',
    'Bahir Dar',
    'Dessie',
    'Jimma',
    'Jijiga',
    'Shashamane',
    'Bishoftu (Debre Zeit)',
    'Arba Minch',
    'Hosaena',
    'Harar',
    'Dilla',
    'Nekemte',
    'Goba',
    'Sodo',
    'Asella',
    'Debre Markos',
    'Kombolcha',
    'Dembi Dolo',
    'Gode',
    'Shire',
    'Assosa',
    'Gambela',
    'Semera',
    'Jinka',
    'Lalibela',
    'Axum',
    'Woldia',
    'Debre Birhan',
    'Butajira',
    'Mojo',
    'Ziway',
    'Sebeta',
    'Holeta',
    'Ambo',
    'Woliso',
    'Welkite',
    'Hossana',
    'Worabe',
    'Kibre Mengist',
    'Yirgalem',
    'Aleta Wondo',
    'Turmi',
    'Konso',
].sort();
